# Generated by Django 4.0.6 on 2022-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="arfr2qd3", max_length=8, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Visa", "Visa"),
                            ("Mastercard", "Mastercard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("RUB", "RUB"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "balance1",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
