# Generated by Django 4.0.6 on 2022-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="gZKer3v4", max_length=8, unique=True
            ),
        ),
    ]
