# Generated by Django 4.0.6 on 2022-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_alter_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="0gKh3h2y", max_length=8, unique=True
            ),
        ),
    ]
