# Generated by Django 4.0.6 on 2022-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0005_alter_wallet_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="balance1",
            new_name="balance",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="3q8zya6f", max_length=8, unique=True
            ),
        ),
    ]
