# Generated by Django 4.0.6 on 2022-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0006_rename_balance1_wallet_balance_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="M2ogejQd", max_length=8, unique=True
            ),
        ),
    ]
