# Generated by Django 4.0.6 on 2022-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0014_wallet_user_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="YvrM0l00", max_length=8, unique=True
            ),
        ),
    ]
