# Generated by Django 4.0.6 on 2022-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0015_alter_wallet_balance_alter_wallet_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transfer_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "PAID"), ("FAILED", "FAILED")],
                        max_length=6,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="H1BZIqja", max_length=8, unique=True
            ),
        ),
    ]
