# Generated by Django 4.0.6 on 2022-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0017_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                auto_created=True,
                default="F9kehZjM",
                max_length=8,
                unique=True,
            ),
        ),
    ]
